{
    "results": {
        "usr/lib/libpytalloc-util_so_2_1_9": {
            "report-functions": [
                "_talloc_reference_loc", 
                "__gmon_start__", 
                "PyErr_SetString", 
                "_talloc_free", 
                "PyType_Ready", 
                "_Jv_RegisterClasses", 
                "PyImport_ImportModule", 
                "talloc_check_name", 
                "PyObject_GetAttrString", 
                "_talloc_steal_loc", 
                "talloc_set_name_const", 
                "__cxa_finalize", 
                "talloc_get_name", 
                "PyErr_NoMemory", 
                "PyCObject_FromVoidPtr", 
                "_ITM_deregisterTMCloneTable", 
                "PyErr_Format", 
                "_ITM_registerTMCloneTable"
            ], 
            "rpm": "pytalloc-2.1.9-1.el7.i686.rpm", 
            "complexity": {
                "r2aa": "failed: ERROR: Cannot find radare2 in PATH"
            }, 
            "hardening-check": {
                " Read-only relocations": "yes", 
                " Position Independent Executable": "no, regular shared library (ignored)", 
                " Stack protected": "no, not found!", 
                " Fortify Source functions": "unknown, no protectable libc functions used", 
                " Immediate binding": "no, not found!"
            }, 
            "filename": "usr/lib/libpytalloc-util.so.2.1.9"
        }, 
        "usr/lib/python2_7/site-packages/talloc_so": {
            "report-functions": [
                "PyType_Ready", 
                "talloc_report_full", 
                "_Jv_RegisterClasses", 
                "talloc_total_blocks", 
                "talloc_enable_null_tracking", 
                "PyString_FromFormat", 
                "PyLong_FromLong", 
                "_pytalloc_get_mem_ctx", 
                "__assert_fail", 
                "Py_InitModule4", 
                "__gmon_start__", 
                "_PyArg_ParseTuple_SizeT", 
                "PyModule_AddObject", 
                "talloc_unlink", 
                "PyObject_Type", 
                "_ITM_deregisterTMCloneTable", 
                "_pytalloc_get_ptr"
            ], 
            "rpm": "pytalloc-2.1.9-1.el7.i686.rpm", 
            "complexity": {
                "r2aa": "failed: ERROR: Cannot find radare2 in PATH"
            }, 
            "hardening-check": {
                " Read-only relocations": "yes", 
                " Position Independent Executable": "no, regular shared library (ignored)", 
                " Stack protected": "no, not found!", 
                " Fortify Source functions": "unknown, no protectable libc functions used", 
                " Immediate binding": "no, not found!"
            }, 
            "filename": "usr/lib/python2.7/site-packages/talloc.so"
        }
    }, 
    "metadata": {
        "spec_data": {
            "Version": " 2.1.9", 
            "Name": " pytalloc", 
            "License": " LGPLv3+", 
            "URL": " http://talloc.samba.org/", 
            "Relocations": " (not relocatable)", 
            "Install Date": " (not installed)", 
            "Build Host": " x86-039.build.eng.bos.redhat.com", 
            "Description": "\nPytalloc libraries for creating python bindings using talloc\n", 
            "Build Date": " Wed 01 Mar 2017 03:57:30 AM EST", 
            "Vendor": " Red Hat, Inc.", 
            "Source RPM": " libtalloc-2.1.9-1.el7.src.rpm", 
            "warning": " /home/jason/fctl/swap/3/pytalloc-2.1.9-1.el7.i686.rpm: Header V3 RSA/SHA256 Signature, key ID fd431d51: NOKEY", 
            "Architecture": " i686", 
            "Signature": " RSA/SHA256, Wed 15 Mar 2017 06:52:11 AM EDT, Key ID 199e2f91fd431d51", 
            "Release": " 1.el7", 
            "Group": " Development/Libraries", 
            "Packager": " Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>", 
            "Summary": " Developer tools for the Talloc library", 
            "Size": " 26028"
        }
    }
}